### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by rohit01** [mrtazz/sensu-heroku-app#1]

**Comment by mrtazz** [comment]
I haven't set it up in a while. What errors are you seeing?

**Comment by rohit01** [comment]
Gem install error for sensu..

Thanks & Regards,

Rohit Gupta
http://www.rohit.io

**Comment by mrtazz** [comment]
I'm not using this anymore. I'll happily accept pull requests to fix the Gemfile but won't actively look into setting this back up.
